import showActive from './globals';
import Bitmap from './bitmap.js';
import Params from './params.js';
import RowButtons from './rowButtons';

export class App {

    constructor() {
        new Params();
        new RowButtons();
        bitmapInstance = new Bitmap();

        document.querySelector('button.make').addEventListener('click', ev => this.makeOutput(ev.target));
        document.querySelector('button.fileUpload').addEventListener('click', ev => showActive(ev.target));
        document.querySelector('button.copy').addEventListener('click', (ev) => {
            showActive(ev.target);
            navigator.clipboard.writeText(document.querySelector('pre').innerText).then(() => {});
        });
    }

    makeOutput(button) {
        showActive(button);

        const pre = document.querySelector('pre');
        const capFileName = fileName.toUpperCase().replace(/[ .]/g, '_');
        pre.innerText = `/*
 * ${fileName}
 *
 * generated by fontEdit – https://github.com/tdausner/fontEdit
 *
 * Font Name: ${fileName}
 * Font Width: ${params.maxDisplayPages} pages
 * Font Size: ${params.maxRows} pixels
 */

#ifndef ${capFileName}
#define ${capFileName}

#include <avr/pgmspace.h>

typedef struct {
    char symbol;
    uint8_t width;
    const uint8_t *bitmap;
} FontData;

`;
        bitmaps.forEach((bitmap, bitmapIndex) => {
            pre.innerText += `static const uint8_t bitmap_${bitmapIndex}[] PROGMEM = {
`;
            const width = bitmap.width;
            const cells = bitmap.cells;
            for (let page = 0; page < params.maxFontPages; page++) {
                let hexText = '';
                for (let col = 0; col < width; col++) {
                    let hex = 0;
                    for (let bit = 0; bit < 8; bit++) {
                        const row = page * 8 + bit;
                        if (row >= cells.length) {
                            hex = 0;
                            break;
                        } else {
                            if (cells[row][col].state) {
                                hex |= (1 << bit);
                            }
                        }
                    }
                    hexText += `0x${hex.toString(16).padStart(2, '0')}, `
                }
                pre.innerText += `    ${hexText}
`;
            }
            pre.innerText += `};
`;
        });

        pre.innerText += `const FontData bitmaps[] PROGMEM = {
`;
        bitmaps.forEach((bitmap, bitmapIndex) => {
            pre.innerText += `    { '${bitmap.name}', sizeof(bitmap_${bitmapIndex}) / ${params.maxFontPages}, bitmap_${bitmapIndex} },
`;
        });

        pre.innerText += `};

#endif /* ${capFileName} */
`;
    }


}