import {showSaveFilePicker} from 'native-file-system-adapter';
import {showActive} from './globals';
import Bitmap from './bitmap';
import RowButtons from './rowButtons';
import FillAndWipeButtonHandler from './fillAndWipeButtonHandler';
import AreaButtonHandler from './areaButtonHandler';
import AreaCopyButtonHandler from './areaCopyButtonHandler';

export class App {

    constructor() {
        new RowButtons();
        bitmapInstance = new Bitmap();

        document.querySelector('button.fileUpload').addEventListener('click', ev => showActive(ev.target));
        document.querySelector('button.make').addEventListener('click', ev => this.makeOutput(ev.target));
        document.querySelector('button.fileDownload').addEventListener('click', ev => this.saveFile(ev.target));
        document.querySelector('button.copy').addEventListener('click', (ev) => {
            showActive(ev.target);
            navigator.clipboard.writeText(document.querySelector('pre').innerText).then(() => {});
        });
        document.querySelector('input.fontNameInput').addEventListener('change', ev => {
            fileName = ev.target.value;
        });
        document.addEventListener('keydown', this.keyHandler);
        document.addEventListener('keyup', this.keyHandler);
    }

    keyHandler(ev) {
        if (activeBitmap !== null) {
            keyPressed = ev.type === 'keydown' ? ev.key : -1;

            if (keyPressed === 'Control' || keyPressed === 'w' || keyPressed === 'W') {
                if (activeBitmap.areaActive) {
                    new AreaButtonHandler(activeBitmap.buttons['area']);
                }
                new FillAndWipeButtonHandler(activeBitmap.buttons['wipe'], false);
            } else if (keyPressed === 'Shift' || keyPressed === 'f' || keyPressed === 'F') {
                if (activeBitmap.areaActive) {
                    new AreaButtonHandler(activeBitmap.buttons['area']);
                }
                new FillAndWipeButtonHandler(activeBitmap.buttons['fill'], true);
            } else if (keyPressed === 'a' || keyPressed === 'A') {
                if (activeBitmap.fillActive) {
                    new FillAndWipeButtonHandler(activeBitmap.buttons['fill'], true);
                }
                if (activeBitmap.wipeActive) {
                    new FillAndWipeButtonHandler(activeBitmap.buttons['wipe'], false);
                }
                new AreaButtonHandler(activeBitmap.buttons['area']);
            } else if (activeBitmap.areaActive && (keyPressed === 'c' || keyPressed === 'C')) {
                new AreaCopyButtonHandler(activeBitmap.buttons['areaCopy']);
            }
        }
    }

    makeOutput(button) {
        showActive(button);

        const pre = document.querySelector('pre');
        const capFileName =
            fileName.replace(/([a-zA-Z])(?=[A-Z])/g, '$1_')
                    .replace(/[^A-Za-z0-9_]/g, '_')
                    .toUpperCase();
        const fontName = fileName.substring(0, fileName.lastIndexOf('.'));
        if (fileHeader !== '') {
            pre.innerText = fileHeader
                .replace(/ \* .*\.h/, ` * ${fileName}`)
                .replace(/Font Name: .*/, `Font Name: ${fontName}`)
                .replace(/Font Height: \d+ pixels/, `Font Height: ${params.maxRows} pixels`);
        } else {
            pre.innerText = `/*
 * ${fileName}
 *
 * generated by fontEdit – https://github.com/tdausner/fontEdit
 *
 * Font Name: ${fontName}
 * Font Height: ${params.maxRows} pixels
 */
`;
        }

        pre.innerText += `#ifndef ${capFileName}
#define ${capFileName}

#include <avr/pgmspace.h>

typedef struct {
    char c;
    uint8_t width;
    const uint8_t *bitmap;
} FontData;

#define FONT_PAGES ${params.maxFontPages}

`;
        const uniqId = parseInt(Date.now() / 1000).toString(16);

        bitmaps.forEach((bitmap, bitmapIndex) => {
            const width = bitmap.width;
            const cells = bitmap.cells;

            pre.innerText += `static const uint8_t bitmap_${uniqId}_${bitmapIndex}[] PROGMEM = {  // '${bitmap.name}' width: ${width}
`;
            for (let page = 0; page < params.maxFontPages; page++) {
                let hexText = '';
                for (let col = 0; col < width; col++) {
                    let hex = 0;
                    for (let bit = 0; bit < 8; bit++) {
                        const row = page * 8 + bit;
                        if (row >= cells.length) {
                            hex = 0;
                            break;
                        } else {
                            if (cells[row][col].state) {
                                hex |= (1 << bit);
                            }
                        }
                    }
                    hexText += `0x${hex.toString(16).padStart(2, '0')}, `
                }
                pre.innerText += `    ${hexText}
`;
            }
            pre.innerText += `};
`;
        });

        const bitmapName = 'bitmaps_' + fontName.replace(/[^A-Za-z0-9_]/g, '_');
        pre.innerText += `static const FontData ${bitmapName}[] PROGMEM = {
`;
        bitmaps.forEach((bitmap, bitmapIndex) => {
            pre.innerText += `    { '${bitmap.name}', sizeof(bitmap_${uniqId}_${bitmapIndex}) / ${params.maxFontPages}, bitmap_${uniqId}_${bitmapIndex} },
`;
        });

        pre.innerText += `};

#endif /* ${capFileName} */
`;
        window.scrollTo({
            top: pre.getBoundingClientRect().top + window.scrollY - 80,
            left: 0,
            behavior: 'smooth'
        });

        document.querySelectorAll('button.fileDownload, button.copy')
                .forEach(button => button.classList.remove('disabled'));
    }

    async saveFile(button) {
        showActive(button);
        try {
            const newHandle = await showSaveFilePicker({
                suggestedName: fileName,
                types: [
                    {
                        description: 'C header file',
                        accept: {
                            'text/plain': ['.h']
                        }
                    }
                ]
            });

            const writableStream = await newHandle.createWritable();
            const pre = document.querySelector('pre');
            await writableStream.write(pre.innerText);
            await writableStream.close();
        } catch (err) {
            console.error(err.name, err.message);
        }
    }
}