import showActive from './globals';
import Bitmap from './bitmap.js';
import Params from './params.js';
import RowButtons from './rowButtons';
import {showSaveFilePicker} from 'native-file-system-adapter';

export class App {

    constructor() {
        new Params();
        new RowButtons();
        bitmapInstance = new Bitmap();

        document.querySelector('button.fileUpload').addEventListener('click', ev => showActive(ev.target));
        document.querySelector('button.make').addEventListener('click', ev => this.makeOutput(ev.target));
        document.querySelector('button.fileDownload').addEventListener('click', ev => this.saveFile(ev.target));
        document.querySelector('button.copy').addEventListener('click', (ev) => {
            showActive(ev.target);
            navigator.clipboard.writeText(document.querySelector('pre').innerText).then(() => {});
        });
    }

    makeOutput(button) {
        showActive(button);

        const pre = document.querySelector('pre');
        const capFileName =
            fileName.replace(/([a-zA-Z])(?=[A-Z])/g, '$1_')
                    .replace('.', '_')
                    .toUpperCase();
        const fontName = fileName.substring(0, fileName.lastIndexOf('.'));
        if (fileHeader !== '') {
            pre.innerText = fileHeader
                .replace(/Font Name: .*?/, `Font Name: ${fontName}`)
                .replace(/Font Height: \d+ pixels/, `Font Height: ${params.maxRows} pixels`);
        } else {
            pre.innerText = `/*
 * ${fileName}
 *
 * generated by fontEdit – https://github.com/tdausner/fontEdit
 *
 * Font Name: ${fontName}
 * Font Height: ${params.maxRows} pixels
 */
`;
        }

        pre.innerText += `#ifndef ${capFileName}
#define ${capFileName}

#include <avr/pgmspace.h>

typedef struct {
    char c;
    uint8_t width;
    const uint8_t *bitmap;
} FontData;

#define FONT_PAGES ${params.maxFontPages}

`;
        bitmaps.forEach((bitmap, bitmapIndex) => {
            const width = bitmap.width;
            const cells = bitmap.cells;

            pre.innerText += `static const uint8_t bitmap_${bitmapIndex}[] PROGMEM = {  // '${bitmap.name}' width: ${width}
`;
            for (let page = 0; page < params.maxFontPages; page++) {
                let hexText = '';
                for (let col = 0; col < width; col++) {
                    let hex = 0;
                    for (let bit = 0; bit < 8; bit++) {
                        const row = page * 8 + bit;
                        if (row >= cells.length) {
                            hex = 0;
                            break;
                        } else {
                            if (cells[row][col].state) {
                                hex |= (1 << bit);
                            }
                        }
                    }
                    hexText += `0x${hex.toString(16).padStart(2, '0')}, `
                }
                pre.innerText += `    ${hexText}
`;
            }
            pre.innerText += `};
`;
        });

        pre.innerText += `const FontData bitmaps[] PROGMEM = {
`;
        bitmaps.forEach((bitmap, bitmapIndex) => {
            pre.innerText += `    { '${bitmap.name}', sizeof(bitmap_${bitmapIndex}) / ${params.maxFontPages}, bitmap_${bitmapIndex} },
`;
        });

        pre.innerText += `};

#endif /* ${capFileName} */
`;
        window.scrollTo({
            top: pre.getBoundingClientRect().top + window.scrollY - 80,
            left: 0,
            behavior: 'smooth'
        });

        document.querySelectorAll('button.fileDownload, button.copy').forEach(button => button.classList.remove('inactive'));
    }

    async saveFile(button) {
        showActive(button);
        try {
            const newHandle = await showSaveFilePicker({
                suggestedName: fileName,
                types: [
                    {
                        description: 'C header file',
                        accept: {
                            'text/plain': ['.h']
                        }
                    }
                ]
            });

            const writableStream = await newHandle.createWritable();
            const pre = document.querySelector('pre');
            await writableStream.write(pre.innerText);
            await writableStream.close();
        } catch (err) {
            console.error(err.name, err.message);
        }
    }
}